version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202104-01
      docker_layer_caching: true
    steps:
      - checkout

      - run:
          name: "Install Docker Compose"
          environment:
            COMPOSE_VERSION: "1.29.2"
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: "Start Building"
          command: |
            ./build.sh
      
      - store_artifacts:
          path: dist/linux.iso

workflows:
  build-workflow:
    jobs:
      - build
