version: 2.1
jobs:
  build-image:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: large
    steps:
      - checkout
      
      - restore_cache:
          keys:
            - buildroot-cache-v15

      - run:
          name: "Start Building"
          command: |
            ./build.sh
      
      - run:
          name: "Boost Node.js and Create State File"
          command: |
            cp 'buildroot-2023.02/output/images/rootfs.iso9660' now/linux.iso
            cd now
            echo "lib86, v86wasm, seabios.bin downloading..."
            wget -q 'https://github.com/copy/v86/releases/download/latest/libv86.js'
            wget -q 'https://github.com/copy/v86/releases/download/latest/v86.wasm'
            wget -q 'https://github.com/copy/v86/raw/master/bios/seabios.bin'
            node index.js

      - run:
          name: "Compress State File"
          when: on_success
          command: |
            sudo apt install zstd --allow-change-held-packages
            zstd --ultra -22 now/linux_state.bin -o now/linux_state.bin.zst

      - save_cache:
          key: buildroot-cache-v15
          paths:
            - "~/br-cache"

      - store_artifacts:
          path: now/linux.iso
          destination: linux.iso
      
      - store_artifacts:
          path: now/linux_state.bin.zst
          destination: linux_state.bin.zst

workflows:
  build-workflow:
    jobs:
      - build-image
