version: 2.1
jobs:
  build-image:
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: true
    resource_class: xlarge
    steps:
      - checkout

      - run:
          name: "Start Building"
          command: |
            ./build.sh
      
      - store_artifacts:
          path: dist/linux.iso

workflows:
  build-workflow:
    jobs:
      - build-image
