version: 2.1
jobs:
  build-image:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: large
    steps:
      - checkout

      - restore_cache:
          keys:
            - buildroot-cache-v10

      - run:
          name: "Start Building"
          command: |
            ./build.sh

      - run:
          name: "Cleaning Before Cache Creation"
          command: |
            rm -rf buildroot-2023.02/buildroot-custom

      - save_cache:
          key: buildroot-cache-v10
          paths:
            - "buildroot-2023.02"
      
      - run:
          name: "Boost nodejs and Create State"
          command: |
            cp 'buildroot-2023.02/output/images/rootfs.iso9660' now/linux.iso
            cd now
            wget 'https://github.com/copy/v86/releases/download/latest/libv86.js'
            wget 'https://github.com/copy/v86/releases/download/latest/v86.wasm'
            wget 'https://github.com/copy/v86/raw/master/bios/seabios.bin'
            node index.js
            ls

      - run:
          name: "Compress State File"
          command: |
            sudo apt install zstd -y --allow-downgrades
            zstd --ultra -22 now/linux_state.bin -o now/linux_state.bin.zst

      - store_artifacts:
          # path: buildroot-2023.02/output/images/rootfs.iso9660
          path: now/linux.iso
          destination: linux.iso
      
      - store_artifacts:
          path: now/linux_state.bin.zst
          destination: linux_state.bin.zst

workflows:
  build-workflow:
    jobs:
      - build-image
