version: 2.1
jobs:
  build-image:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: large
    steps:
      - checkout

      - restore_cache:
          keys:
            - buildroot-cache-v7

      - run:
          name: "Start Building"
          command: |
            ./build.sh

      - run:
          name: "Cleaning Before Cache Creation"
          command: |
            rm -rf buildroot-2023.02/buildroot-custom

      - save_cache:
          key: buildroot-cache-v7
          paths:
            - "buildroot-2023.02"

      - store_artifacts:
          path: dist/linux.iso

workflows:
  build-workflow:
    jobs:
      - build-image
