version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202104-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: "Start Building"
          command: "./build.sh"
      - store_artifacts:
          path: dist/linux.iso

workflows:
  build-workflow:
    jobs:
      - build
