version: 2.1
jobs:
  build-image:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: large
    steps:
      - checkout
      
      - restore_cache:
          keys:
            - buildroot-cache-v18

      - run:
          name: "Start Building"
          command: |
            sudo apt install --allow-change-held-packages gcc-multilib
            ./build.sh
      
      - run:
          name: "Boost Node.js and Create State File"
          command: |
            cp 'buildroot-2023.02/output/images/rootfs.iso9660' scripts/linux.iso
            cd scripts
            echo "v86wasm, seabios.bin downloading..."
            wget -q 'https://github.com/copy/v86/releases/download/latest/v86.wasm'
            wget -q 'https://github.com/copy/v86/raw/master/bios/seabios.bin'
            node boot.js

      - run:
          name: "Compress State File"
          when: on_success
          command: |
            sudo apt install --allow-change-held-packages zstd
            zstd --ultra -22 scripts/linux_state.bin -o scripts/linux_state.bin.zst

      - save_cache:
          key: buildroot-cache-v18
          paths:
            - "~/br-cache"

      - store_artifacts:
          path: scripts/linux.iso
          destination: linux.iso
      
      - store_artifacts:
          path: scripts/linux_state.bin.zst
          destination: linux_state.bin.zst
      
      - store_artifacts:
          path: /home/circleci/project/buildroot-2023.02/output/images/bzImage
          destination: linux.bzImage

workflows:
  build-workflow:
    jobs:
      - build-image
