#!/bin/sh

# export PATH="$PATH:/usr/local/lib/nodejs/bin"

export HISTFILE='/tmp/.ash_history'
export NODE_NO_READLINE=1

PS1='\W$ '
HOME='/root/'

cd ~

echo
echo "|=================|"
echo "| =  Now Ready  = |"
echo "|=================|"
echo