#!/bin/sh

# Nodejs
export PATH=/usr/local/lib/nodejs/bin:$PATH

mount -a

echo 3 > /proc/sys/vm/drop_caches

PS1='\W$ '
HOME='/root/'

echo
echo "|=================|"
echo "| =  Now Ready  = |"
echo "|=================|"
echo

cd $HOME