name: Build image
run-name: ${{ github.actor }} is creating now linux image 🚀
on: [push]
jobs:
  Build:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          
      - name: Install packages
        run: |
          brew install docker docker-machine
        
      - name: Start building
        run: |
          ./build.sh
